### ISSUE TITLE
Only on Windows: Error running filter replace_ampersands.lua:13: attempt to index a nil value (field 'c')

### ISSUE THREAD

**Issue by mariusbarth** [crsh/rmdfiltr#13]
Hi @crsh,

this is a problem originally reporterd by @kbading. Only on Windows, using parameter `lang: de-DE` fails with the most recent versions of R (4.2.2), pandoc (2.19.2) and rmarkdown (2.19). The error message is:

```
"C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/pandoc" +RTS -K512m -RTS test.knit.md --to latex --from markdown+autolink_bare_uris+tex_math_single_backslash+raw_attribute --output test.tex --lua-filter "C:\Users\MARIUS~1\AppData\Local\R\WIN-LI~1\4.2\bookdown\RMARKD~1\lua\CUSTOM~1.LUA" --lua-filter "C:\Users\MARIUS~1\AppData\Local\R\WIN-LI~1\4.2\RMARKD~1\RMARKD~1\lua\PAGEBR~1.LUA" --lua-filter "C:\Users\MARIUS~1\AppData\Local\R\WIN-LI~1\4.2\RMARKD~1\RMARKD~1\lua\LATEX-~1.LUA" --embed-resources --standalone --highlight-style tango --pdf-engine pdflatex --include-in-header "C:\Users\MARIUS~1\AppData\Local\R\WIN-LI~1\4.2\papaja\RMARKD~1\TEMPLA~1\apa6\RESOUR~1\APA6_H~1.TEX" --variable graphics --wrap preserve --csl "C:\Users\MARIUS~1\AppData\Local\R\WIN-LI~1\4.2\papaja\rmd\apa6.csl" --citeproc --lua-filter "C:/Users/Marius Barth/AppData/Local/R/win-library/4.2/rmdfiltr/replace_ampersands.lua" --lua-filter "C:/Users/Marius Barth/AppData/Local/R/win-library/4.2/rmdfiltr/wordcount.lua" --lua-filter "C:/Users/Marius Barth/AppData/Local/R/win-library/4.2/papaja/lua/parse_metadata.lua" --variable "documentclass:apa6" --variable "classoption:man" --variable "lang:de-DE" --variable "subparagraph:yes" --variable "block-headings:no" --include-in-header "C:\Users\MARIUS~1\AppData\Local\Temp\RtmpU5bQ5X\includes_12a028fc1da9.tex" 
Error running filter C:/Users/Marius Barth/AppData/Local/R/win-library/4.2/rmdfiltr/replace_ampersands.lua:
.../Local/R/win-library/4.2/rmdfiltr/replace_ampersands.lua:13: attempt to index a nil value (field 'c')
stack traceback:
Fehler: pandoc document conversion failed with error 83
Ausführung angehalten
```

Here is a reproducible example (finishes on Ubuntu, fails on Windows)
[test.zip](https://github.com/crsh/rmdfiltr/files/10448019/test.zip)

**Comment by crsh** [comment]
Seems odd that this would be OS-dependend. Are you using the same versions of `pandoc` on both machines?

**Comment by mariusbarth** [comment]
Yes., it's 2.19.2 on both machines

**Comment by crsh** [comment]
Is there any chance that there are multipe versions of `pandoc` installed on one of the computers? For example, one shipped with RStudio and one installed manually?

**Comment by mariusbarth** [comment]
I indeed had an alternate version of pandoc installed (2.11) on the Ubuntu machine. However, even after removing that pandoc version, I can still render the document with RStudio's pandoc, which is 2.19.2 (as returned from `rmarkdown::pandoc_version()`). On Windows, I only have 2.19.2, also returned from `pandoc_version()`).

**Comment by crsh** [comment]
Thanks for the additional information. I think this is a duplicate of #11. Can you check whether it works after reinstalling from this repository?

**Comment by mariusbarth** [comment]
I just double checked on both Linux and Windows. After running `remotes::install_github("crsh/rmdfiltr")`, everything works as expected.

**Comment by crsh** [comment]
Great, thanks. I'll try to submit to CRAN soon.
